#pragma once
#define LNX_H_KEYBOARD_INPUT




enum LnxKeyboardKeys : uint16 {
	LNX_KEY_SPACE         = 32,
	LNX_KEY_APOSTROPHE    = 39,
	LNX_KEY_COMMA         = 44,
	LNX_KEY_MINUS         = 45,
	LNX_KEY_PERIOD        = 46,
	LNX_KEY_SLASH         = 47,
	LNX_KEY_0             = 48,
	LNX_KEY_1             = 49,
	LNX_KEY_2             = 50,
	LNX_KEY_3             = 51,
	LNX_KEY_4             = 52,
	LNX_KEY_5             = 53,
	LNX_KEY_6             = 54,
	LNX_KEY_7             = 55,
	LNX_KEY_8             = 56,
	LNX_KEY_9             = 57,
	LNX_KEY_SEMICOLON     = 59,
	LNX_KEY_EQUAL         = 61,
	LNX_KEY_A             = 65,
	LNX_KEY_B             = 66,
	LNX_KEY_C             = 67,
	LNX_KEY_D             = 68,
	LNX_KEY_E             = 69,
	LNX_KEY_F             = 70,
	LNX_KEY_G             = 71,
	LNX_KEY_H             = 72,
	LNX_KEY_I             = 73,
	LNX_KEY_J             = 74,
	LNX_KEY_K             = 75,
	LNX_KEY_L             = 76,
	LNX_KEY_M             = 77,
	LNX_KEY_N             = 78,
	LNX_KEY_O             = 79,
	LNX_KEY_P             = 80,
	LNX_KEY_Q             = 81,
	LNX_KEY_R             = 82,
	LNX_KEY_S             = 83,
	LNX_KEY_T             = 84,
	LNX_KEY_U             = 85,
	LNX_KEY_V             = 86,
	LNX_KEY_W             = 87,
	LNX_KEY_X             = 88,
	LNX_KEY_Y             = 89,
	LNX_KEY_Z             = 90,
	LNX_KEY_LEFT_BRACKET  = 91,
	LNX_KEY_BACKSLASH     = 92,
	LNX_KEY_RIGHT_BRACKET = 93,
	LNX_KEY_GRAVE_ACCENT  = 96,
	LNX_KEY_WORLD_1       = 161,
	LNX_KEY_WORLD_2       = 162,


	LNX_KEY_ESCAPE        = 256,
	LNX_KEY_ENTER         = 257,
	LNX_KEY_TAB           = 258,
	LNX_KEY_BACKSPACE     = 259,
	LNX_KEY_INSERT        = 260,
	LNX_KEY_DELETE        = 261,
	LNX_KEY_RIGHT         = 262,
	LNX_KEY_LEFT          = 263,
	LNX_KEY_DOWN          = 264,
	LNX_KEY_UP            = 265,
	LNX_KEY_PAGE_UP       = 266,
	LNX_KEY_PAGE_DOWN     = 267,
	LNX_KEY_HOME          = 268,
	LNX_KEY_END           = 269,
	LNX_KEY_CAPS_LOCK     = 280,
	LNX_KEY_SCROLL_LOCK   = 281,
	LNX_KEY_NUM_LOCK      = 282,
	LNX_KEY_PRINT_SCREEN  = 283,
	LNX_KEY_PAUSE         = 284,
	LNX_KEY_F1            = 290,
	LNX_KEY_F2            = 291,
	LNX_KEY_F3            = 292,
	LNX_KEY_F4            = 293,
	LNX_KEY_F5            = 294,
	LNX_KEY_F6            = 295,
	LNX_KEY_F7            = 296,
	LNX_KEY_F8            = 297,
	LNX_KEY_F9            = 298,
	LNX_KEY_F10           = 299,
	LNX_KEY_F11           = 300,
	LNX_KEY_F12           = 301,
	LNX_KEY_F13           = 302,
	LNX_KEY_F14           = 303,
	LNX_KEY_F15           = 304,
	LNX_KEY_F16           = 305,
	LNX_KEY_F17           = 306,
	LNX_KEY_F18           = 307,
	LNX_KEY_F19           = 308,
	LNX_KEY_F20           = 309,
	LNX_KEY_F21           = 310,
	LNX_KEY_F22           = 311,
	LNX_KEY_F23           = 312,
	LNX_KEY_F24           = 313,
	LNX_KEY_F25           = 314,
	LNX_KEY_KP_0          = 320,
	LNX_KEY_KP_1          = 321,
	LNX_KEY_KP_2          = 322,
	LNX_KEY_KP_3          = 323,
	LNX_KEY_KP_4          = 324,
	LNX_KEY_KP_5          = 325,
	LNX_KEY_KP_6          = 326,
	LNX_KEY_KP_7          = 327,
	LNX_KEY_KP_8          = 328,
	LNX_KEY_KP_9          = 329,
	LNX_KEY_KP_DECIMAL    = 330,
	LNX_KEY_KP_DIVIDE     = 331,
	LNX_KEY_KP_MULTIPLY   = 332,
	LNX_KEY_KP_SUBTRACT   = 333,
	LNX_KEY_KP_ADD        = 334,
	LNX_KEY_KP_ENTER      = 335,
	LNX_KEY_KP_EQUAL      = 336,
	LNX_KEY_LEFT_SHIFT    = 340,
	LNX_KEY_LEFT_CTRL     = 341,
	LNX_KEY_LEFT_ALT      = 342,
	LNX_KEY_LEFT_SUPER    = 343,
	LNX_KEY_RIGHT_SHIFT   = 344,
	LNX_KEY_RIGHT_CTRL    = 345,
	LNX_KEY_RIGHT_ALT     = 346,
	LNX_KEY_RIGHT_SUPER   = 347,
	LNX_KEY_MENU          = 348,

	LNX_KEY_LAST          = 0xFFFF
};


