#pragma once
#define LNX_H_MOUSE_INPUT




enum LnxMouseButtons {
	LNX_MOUSE_BUTTON_1      = 0,		//Same as LNX_MOUSE_BUTTON_RIGHT
	LNX_MOUSE_BUTTON_2      = 1,		//Same as LNX_MOUSE_BUTTON_LEFT
	LNX_MOUSE_BUTTON_3      = 2,		//Same as LNX_MOUSE_BUTTON_MIDDLE
	LNX_MOUSE_BUTTON_4      = 3,
	LNX_MOUSE_BUTTON_5      = 4,
	LNX_MOUSE_BUTTON_6      = 5,
	LNX_MOUSE_BUTTON_7      = 6,
	LNX_MOUSE_BUTTON_8      = 7,
	LNX_MOUSE_BUTTON_RIGHT  = LNX_MOUSE_BUTTON_1,
	LNX_MOUSE_BUTTON_LEFT   = LNX_MOUSE_BUTTON_2,
	LNX_MOUSE_BUTTON_MIDDLE = LNX_MOUSE_BUTTON_3
};
