import os, sys
#TODO read paths from config file
#TODO make this script an executable



def run(mode:str):
    print()
    pf = mode[0]
    cf = mode[1]
    PF = 'Linux' if pf == 'l' else 'Windows'
    CF = 'Debug' if cf == 'd' else 'Release'

    npf =       'w' if pf == 'l' else 'l'
    ncf =       'r' if cf == 'd' else 'd'
    NPF = 'Windows' if pf == 'l' else 'Linux'
    NCF = 'Release' if cf == 'd' else 'Debug'

    with open('./.engine/.ptoe', 'r') as f: ptoe = f.read()




    #Update tasks.json
    with open('.vscode/tasks.json', 'w') as f:
        f.write(
            f'\n//################################################################'
            f'\n// This file was generated by { ptoe }/Tools/Setup/UpdateBuild'
            f'\n// Changes could be overwritten without notice'
            f'\n//################################################################'
            f'\n'
            f'\n'
            f'\n{{'
            f'\n    "version": "2.0.0",'
            f'\n    "tasks": ['
            f'\n        {{'
            f'\n            "type": "shell",'
            f'\n            "label": "{ PF }  |  { CF }  |  Build\",'
            f'\n            "command": "{ ptoe }/Tools/Build/lynxg++",'
            f'\n            "args": [ "-f=.engine/Build.Application.sh" ],'
            f'\n            "problemMatcher": [ "$gcc" ],'
            f'\n            "options": {{ "cwd": "${{workspaceFolder}}" }},'
            f'\n            "group": "build"'
            f'\n        }},'
            f'\n        {{'
            f'\n            "type": "shell",'
            f'\n            "label": "{ PF }  |  { CF }  |  Clear\",'
            f'\n            "command": "python3",'
            f'\n            "args": [ "{ ptoe }/Alloy_tmp.py", "clear" ],'
            f'\n            "problemMatcher": [ ],'
            f'\n            "options": {{ "cwd": "${{workspaceFolder}}" }},'
            f'\n            "group": "build"'
            f'\n        }},'
            f'\n        {{'
            f'\n            "type": "shell",'
            f'\n            "label": "{ PF }  |  { CF }  |  Clear && Rebuild\",'
            f'\n            "command": "sh",'
            f'\n            "args": [ "-c", "python3 Lynx/Alloy_tmp.py clear && Lynx/Tools/Build/lynxg++ -f=.engine/Build.Application.sh" ],'
            f'\n            "problemMatcher": [ ],'
            f'\n            "options": {{ "cwd": "${{workspaceFolder}}" }},'
            f'\n            "group": "build"'
            f'\n        }},'
            f'\n        {{'
            f'\n            "type": "shell",'
            f'\n            "label": " > Switch to { NPF }",'
            f'\n            "command": "python3",'
            f'\n            "args": ["{ ptoe }/Tools/Setup/UpdateBuild.py", "{ npf }{ cf }"],'
            f'\n            "problemMatcher": [ ],'
            f'\n            "options": {{ "cwd": "${{workspaceFolder}}" }},'
            f'\n            "group": "build"'
            f'\n        }},'
            f'\n        {{'
            f'\n            "type": "shell",'
            f'\n            "label": " > Switch to { NCF }",'
            f'\n            "command": "python3",'
            f'\n            "args": ["{ ptoe }/Tools/Setup/UpdateBuild.py", "{ pf }{ ncf }"],'
            f'\n            "problemMatcher": [ ],'
            f'\n            "options": {{ "cwd": "${{workspaceFolder}}" }},'
            f'\n            "group": "build"'
            f'\n        }}'
            f'\n    ]'
            f'\n}}'
        )




    #Update debug macro
    with open('./.engine/conf.hpp', 'w') as f:
        f.write(
            f'\n//####################################################################################'
            f'\n// This file was generated by { ptoe }/Tools/Setup/UpdateBuild.py'
            f'\n// Changes could be overwritten without notice'
            f'\n//####################################################################################\n'
            f'\n'
            f'\n'
            f'\n#pragma once'
            f'\n#ifndef __INTELLISENSE__'
            f'\n    #error "Something went wrong. This header cannot be used during compilation"'
            f'\n#endif'
            f'\n'
            f'\n#define LNX_{ "DBG" if cf == "d" else "RLS" }'
        )








if(len(sys.argv) == 2): run(sys.argv[1])
else: sys.exit('Incorrect number of arguments')