import os, re
#TODO read paths from config file
#TODO make this script an executable



def run(dir):
    with open('./.engine/.pf', 'r') as f:
        pf = f.read(1)
    with open('./.engine/.cf', 'r') as f:
        cf = f.read(1)
    with open('./.engine/.etop', 'r') as f:
        etop = f.read()

    def getPf():
        return "Linux" if pf == "l" else "Windows"
    def getCf():
        return "Debug" if cf == "d" else "Release"



    os.chdir(dir) #FIXME REMOVE



    #Read and parse tasks
    with open('./.vscode/tasks.json', 'r') as f:
        s = re.sub(r'("args"\s*:\s*\[\s*"--mode=)[l|w][d|r|s]"', r'\g<1>' + pf + cf + '"',
            re.sub(r'("label"\s*:\s*")\w+  \|  \w+(  \|  Build (\w| )+")', r'\g<1>' + getPf() + '  |  ' + getCf() + r'\g<2>',
            re.sub(
                r'("label"\s*:\s*" > Switch to )(Linux|Windows)("(.|\n)*?"'
                r'.*?Lynx\/Tools\/Setup\/SetPlatform\.py"\s*,\s*")(l|w)"',
                r'\g<1>' + ("Windows" if pf == "l" else "Linux") + r'\g<3>' + ('w' if pf == 'l' else 'l') + '"',
            re.sub(
                r'("label"\s*:\s*" > Switch to )(Debug|Release)("(.|\n)*?"'
                r'.*?Lynx\/Tools\/Setup\/SetConfiguration\.py"\s*,\s*")(d|r)"',
                r'\g<1>' + ("Release" if cf == "d" else "Debug") + r'\g<3>' + ('r' if cf == 'd' else 'd') + '"',
            f.read()
        ))))


    #Update tasks.json
    with open('./.vscode/tasks.json', 'w') as f:
        f.write(s)




    #Update debug macro
    with open('./.engine/conf.hpp', 'w') as f:
        f.write(
            '\n//####################################################################################'
            '\n// This file was generated by Lynx/Tools/Setup/UpdateBuild.py'
            '\n// Changes could be overwritten without notice'
            '\n//####################################################################################\n'
            '\n\n'
            '\n#pragma once'
            '\n#ifndef __INTELLISENSE__'
            '\n    #error "Something went wrong. This header cannot be used during compilation"'
            '\n#endif'
            '\n'
        )
        f.write('\n#define ' + ('LNX_DEBUG' if cf == 'd' else 'LNX_RELEASE'))
