
//####################################################################################
// This file was generated by Lynx/shaders/GlslToCpp.py
// Changes could be overwritten without notice
//####################################################################################

#pragma once
#include "Lynx/Core/Render/Shaders/Shader_t.hpp"



namespace lnx::shd{
	struct Border2 : public Shader_b {
		static Shader_b::Layout layout;
		static uint32 pipelineIndex;


		struct outcol_t : public ShaderElm_b<eStorage> {
			outcol_t() {
				ShaderElm_b::bind = 0;
			}
		} outcol;