
//####################################################################################
// This file was generated by Lynx/shaders/GlslToCpp.py
// Changes could be overwritten without notice
//####################################################################################

#pragma once
#include "Lynx/Core/Render/Shaders/ShaderInterface_t.hpp"



namespace lnx::shd{
    struct FloatToIntBuffer : public ShaderInterface_b {
        static ShaderInterface_b::Layout layout;
        static uint32 pipelineIndex;