import sys, os
#TODO code cleanup

def run(dir):

	def getPf():
		return "Linux" if opts.pf() == "l" else "Windows"
	def getTp():
		return "Debug" if opts.tp() == "d" else "Release"


	enginePath_ = os.path.abspath('.')
	os.chdir(dir)
	import BuildOptions as opts
	#import importlib.util
	# spec = importlib.util.spec_from_file_location("BuildOptions.BuildOptions", enginePath_ + '/Build/BuildOptions/BuildOptions.py')
	# foo = importlib.util.module_from_spec(spec)
	# spec.loader.exec_module(foo)

	#Open tasks file
	with open("./.vscode/tasks.json", "r") as f:

		#Find user build
		while(f.read(1) != '['): pass
		while(f.read(1) != '['): pass

		#read user build
		userBuild = ''
		n = 1
		while(n > 0):
		    c = f.read(1)
		    if(c == '['): n += 1
		    elif(c == ']'): n -= 1
		    userBuild += c

	try:
		plf = getPf()
	except FileNotFoundError:
		plf = ''
	try:
		typ = getTp()
	except FileNotFoundError:
		typ = ''



	with open("./.vscode/tasks.json", "w") as f:
		f.write("""
		//This file was generated by the engine
		//Only modify the options inside the "Build application" task args
		//Other changes could be overwritten without any advise or cause the program to behave uncorreclty
		{
		    "version": "2.0.0",
		    "tasks": [
		        {
		            "type": "shell",
		            "label": \"""" + plf + "  |  " + typ + """  |  Build Application",
		            "command": \"""" + opts.enginePath() + """/Build/lux_g++",
		            "args": [""" + userBuild + """,
		            "problemMatcher": [ "$gcc" ],
		            "options": { "cwd": "${workspaceFolder}" },
		            "group": { "kind": "build", "isDefault": true }
		        },
		        {
		            "type": "shell",
		            "label": \"""" + plf + "  |  " + typ + """  |  Build LuxEngine\",
		            "command": "/usr/bin/g++",
		            "args": [
		                //Source files
				            "-xc++", \"""" + opts.enginePath() + """/LuxEngine/LuxEngine_build.cpp",\n""" +\
		                    (opts.getDebugOptions() if opts.tp() == "d" else opts.getReleaseOptions()) + """,
		                //Engine
		                    "-std=c++2a", "-mavx", "-pipe", "-pthread",
		                    "-I""" + opts.enginePath() + """\",
		                    "-Wall",\n""" +\
		                    opts.getEngineDeps() + """,
		                //Output
							"-c", "-o", \"""" + opts.enginePath() + '/Build/' + plf + '/LuxEngine' + typ + """\"
		            ],
		            "problemMatcher": [ "$gcc" ],
		            "options": { "cwd": "${workspaceFolder}" },
		            "group": { "kind": "build", "isDefault": true }
		        },
		        {
		            "type": "shell",
		            "label": " > Switch to """ + ("Windows" if opts.pf() == "l" else "Linux") + """\",
		            "command": "python3",
		            "args": [
		                \"""" + opts.enginePath() + """/Build/SetPlatform.py",
		                \"""" + ("w" if opts.pf() == "l" else "l") + """\",
		            ],
		            "problemMatcher": [ ],
		            "options": { "cwd": "${workspaceFolder}" },
		            "group": { "kind": "build", "isDefault": true }
		        },
		        {
		            "type": "shell",
		            "label": " > Switch to """ + ("Release" if opts.tp() == "d" else "Debug") + """\",
		            "command": "python3",
		            "args": [
		                \"""" + opts.enginePath() + """/Build/SetType.py",
		                \"""" + ("r" if opts.tp() == "d" else "d") + """\"
		            ],
		            "problemMatcher": [ ],
		            "options": { "cwd": "${workspaceFolder}" },
		            "group": { "kind": "build", "isDefault": true }
		        }
		    ]
		}\n""")